### PR TITLE
Add giscus

### PR DESCRIPTION
**Pull request by hexylena**
per @pmenzel @pvanheus discussion

Preview Locally | On Github
--- | ---
image| image

### CODE REVIEW

**Comment by pmenzel** [comment]
did you see a way to add buttons for text formatting / emojis to the giscus input field? I only see the button for switching to plain text

grafik

**Review by pmenzel — APPROVED** [review]
looks great! thanks a lot!

**Comment by hexylena** [comment]
Looks like it's a known issue/feature request: https://github.com/giscus/giscus/issues/879

**Comment by pmenzel** [comment]
ok, no worries!

**Pull request merged**
