### PR TITLE
Add external link indicator, remove testing external blogpost

### PR DESCRIPTION
**Pull request by hexylena**
image

### CODE REVIEW

**Comment by pmenzel** [comment]
make the icon a bit bigger? maybe 1.5em?

**Comment by pmenzel** [comment]
Interestingly, it now says "Waiting on code owner review from ubinfie/editorial-board **and/or** ubinfie/website".
I think it should be **and** as the PR covers different files that are CODEOWNED by both groups (without overlap).

**Comment by hexylena** [comment]
@pmenzel yes, you're right, that's a _limitation_ of the [github codeowners system](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners#codeowners-and-branch-protection). I do not think there is a way to accomplish what you want, on GitHub. (Though I am absolutely in agreement that that would be the ideal implementation, and not or.)

**Comment by hexylena** [comment]
I'm not actually sure how to scale that, given the current implementation in CCS. I'll have a think.

**Comment by pmenzel** [comment]
> I'm not actually sure how to scale that, given the current implementation in CCS. I'll have a think.

Ah sorry, I thought the height is limited by the current CSS height (1em). But now I see that the PNG image just isn't that big to begin with.

Then just leave it like it is now. Or maybe just use the link emoji 🔗?

**Comment by hexylena** [comment]
Emoji yes, that's better.

**Comment by pmenzel** [comment]
beautiful!

**Review by pmenzel — APPROVED** [review]
lgtm!

**Comment by pmenzel** [comment]
The emoji looked better in your screenshot compared with my Firefox.. :) 
image

**Pull request merged**
